import type { Policy } from "@/types";
import { formatDate, getRiskLabel } from "@/lib/utils";

/**
 * Generate a Markdown report for a policy analysis and trigger download.
 */
export function exportAnalysisReport(policy: Policy) {
  if (!policy.analysis) return;

  const a = policy.analysis;
  const riskEmoji =
    a.riskLevel === "low"
      ? "🟢"
      : a.riskLevel === "medium"
      ? "🟡"
      : a.riskLevel === "high"
      ? "🟠"
      : "🔴";

  const lines: string[] = [
    `# Policy Analysis Report`,
    ``,
    `**Policy:** ${policy.title}`,
    `**Category:** ${policy.category}`,
    `**Analyzed:** ${formatDate(a.analyzedAt)}`,
    `**Status:** ${policy.status}`,
    ``,
    `---`,
    ``,
    `## ${riskEmoji} Risk Assessment`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Risk Score | **${a.riskScore}**/100 |`,
    `| Risk Level | **${a.riskLevel.toUpperCase()}** |`,
    `| Word Count | ${a.wordCount.toLocaleString()} |`,
    `| Reading Time | ~${a.readingTime} min |`,
    ``,
    `---`,
    ``,
    `## Summary`,
    ``,
    a.summary,
    ``,
    `## Compliance Status`,
    ``,
    a.complianceStatus,
    ``,
    `---`,
    ``,
    `## Key Findings (${a.keyFindings.length})`,
    ``,
  ];

  for (const f of a.keyFindings) {
    const sevEmoji =
      f.severity === "low"
        ? "🟢"
        : f.severity === "medium"
        ? "🟡"
        : f.severity === "high"
        ? "🟠"
        : "🔴";
    lines.push(`### ${sevEmoji} ${f.title}`);
    lines.push(``);
    lines.push(`- **Type:** ${f.type}`);
    lines.push(`- **Severity:** ${f.severity}`);
    if (f.section) lines.push(`- **Section:** ${f.section}`);
    lines.push(``);
    lines.push(f.description);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);
  lines.push(`## Recommendations (${a.recommendations.length})`);
  lines.push(``);

  a.recommendations.forEach((rec, i) => {
    lines.push(`${i + 1}. ${rec}`);
  });

  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(
    `*Generated by AI Policy Navigator on ${new Date().toLocaleDateString()}*`
  );

  const markdown = lines.join("\n");
  const blob = new Blob([markdown], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${policy.title.replace(/[^a-zA-Z0-9]/g, "_")}_report.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
